# Generated by Django 5.0.2 on 2024-04-20 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ubicacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricula', models.CharField(max_length=20)),
                ('Trafico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botTelegram.trafico')),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('Licencia', models.CharField(max_length=100)),
                ('Vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='botTelegram.vehiculo')),
            ],
        ),
    ]
