# Generated by Django 5.0.2 on 2024-04-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botTelegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafico',
            name='Fecha',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='trafico',
            name='IntensidadTrafico',
            field=models.IntegerField(default=0),
        ),
    ]
